### ISSUE TITLE
urllib2.HTTPError: HTTP Error 302: Found

### ISSUE THREAD

**Issue by antani** [manasg/gae-log-fetcher#3]
Getting this error with valid configuration :
ubuntu@ip-10-231-62-33:~/gae-log-fetcher$ python ./fetcher.py gae.log
Traceback (most recent call last):
  File "./fetcher.py", line 239, in <module>
    fetch_logs(get_time_period(), RECOVERY_LOG, username, password, app_name, version_ids, offset, dump, append)
  File "./fetcher.py", line 129, in fetch_logs
    remote_api_stub.ConfigureRemoteApi(None, '/remote_api', f, app_name)
  File "/home/ubuntu/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 725, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/home/ubuntu/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 568, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, *_urlargs)
  File "/home/ubuntu/google_appengine/google/appengine/tools/appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 302: Found

**Comment by antani** [comment]
More logs-
ubuntu@ip-10-231-62-33:~/gae-log-fetcher$ python ./fetcher.py --gae_config fetcher.conf gae.log
2014-07-14 08:48:21,057 - root - ERROR - Dreadful exception :
Traceback (most recent call last):
  File "./fetcher.py", line 129, in fetch_logs
    remote_api_stub.ConfigureRemoteApi(None, '/remote_api', f, app_name)
  File "/home/ubuntu/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 725, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/home/ubuntu/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 568, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, *_urlargs)
  File "/home/ubuntu/google_appengine/google/appengine/tools/appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 302: Found
2014-07-14 08:48:21,059 - root - INFO - Successfully authenticated
2014-07-14 08:48:21,059 - root - INFO - Fetching logs from 2014-07-14 01:44:00-07:00 to 2014-07-14 01:45:00-07:00 (GAE TZ)
2014-07-14 08:48:21,059 - root - INFO - Interval : 1405302240 - 1405302250
2014-07-14 08:48:21,059 - root - ERROR - Something went wrong
Traceback (most recent call last):
  File "./fetcher.py", line 173, in fetch_logs
    offset=offset):
  File "/home/ubuntu/google_appengine/google/appengine/datastore/datastore_rpc.py", line 103, in positional_wrapper
    return wrapped(_args, **kwds)
  File "/home/ubuntu/google_appengine/google/appengine/api/logservice/logservice.py", line 884, in fetch
    request.set_app_id(os.environ['APPLICATION_ID'])
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'APPLICATION_ID'
2014-07-14 08:48:21,061 - root - INFO - Retrieved 0 logs. Done.

**Comment by manasg** [comment]
Hi 
Does the APPID in fetcher.conf match what is configured on GAE?

**Comment by antani** [comment]
Thanks for replying Manas, I tried with and without appspot

**Comment by manasg** [comment]
I am not sure what's the problem then. Honestly, I haven't touched GAE in almost a year now. If you want the ownership of this project - I am happy to add you as a collaborator :)

**Comment by antani** [comment]
I am not sure what is causing this but I will try to find out - please go
ahead and make me contributor :)

Thanks,

Ved

**Comment by manasg** [comment]
Added you as a collaborator.
