### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by a4fr** [manasg/gae-log-fetcher#6]
I wan to test your app, but raise error 404:

``` python
Traceback (most recent call last):
  File "fetcher.py", line 242, in <module>
    fetch_logs(get_time_period(), RECOVERY_LOG, username, password, app_name, version_ids, offset, dump, append)
  File "fetcher.py", line 131, in fetch_logs
    remote_api_stub.ConfigureRemoteApi(None, REMOTE_API_PATH, f, app_name, secure=True)
  File "/home/ali/bin/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 874, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/home/ali/bin/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 569, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "/home/ali/bin/google_appengine/google/appengine/tools/appengine_rpc.py", line 393, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

I don't undrestand why!
Could you help me?

**Comment by a4fr** [comment]
I find this logs in **Monitoring>Logs** GAE:

![screenshot from 2015-07-26 10 46 02](https://cloud.githubusercontent.com/assets/6317026/8892803/cb6a9e24-3383-11e5-8f3a-e50d14c1d024.png)
